package org.purevalue.mmon

object BootstrapData {
  val sp500Companies:List[Company] = List(
    Company("MMM", "3M Company", "Industrials"),
    Company("AOS", "A.O. Smith Corp", "Industrials"),
    Company("ABT", "Abbott Laboratories", "Health Care"),
    Company("ABBV", "AbbVie Inc.", "Health Care"),
    Company("ACN", "Accenture plc", "Information Technology"),
    Company("ATVI", "Activision Blizzard", "Information Technology"),
    Company("AYI", "Acuity Brands Inc", "Industrials"),
    Company("ADBE", "Adobe Systems Inc", "Information Technology"),
    Company("AAP", "Advance Auto Parts", "Consumer Discretionary"),
    Company("AMD", "Advanced Micro Devices Inc", "Information Technology"),
    Company("AES", "AES Corp", "Utilities"),
    Company("AET", "Aetna Inc", "Health Care"),
    Company("AMG", "Affiliated Managers Group Inc", "Financials"),
    Company("AFL", "AFLAC Inc", "Financials"),
    Company("A", "Agilent Technologies Inc", "Health Care"),
    Company("APD", "Air Products & Chemicals Inc", "Materials"),
    Company("AKAM", "Akamai Technologies Inc", "Information Technology"),
    Company("ALK", "Alaska Air Group Inc", "Industrials"),
    Company("ALB", "Albemarle Corp", "Materials"),
    Company("ARE", "Alexandria Real Estate Equities Inc", "Real Estate"),
    Company("ALXN", "Alexion Pharmaceuticals", "Health Care"),
    Company("ALGN", "Align Technology", "Health Care"),
    Company("ALLE", "Allegion", "Industrials"),
    Company("AGN", "Allergan, Plc", "Health Care"),
    Company("ADS", "Alliance Data Systems", "Information Technology"),
    Company("LNT", "Alliant Energy Corp", "Utilities"),
    Company("ALL", "Allstate Corp", "Financials"),
    Company("GOOGL", "Alphabet Inc Class A", "Information Technology"),
//    Company("GOOG", "Alphabet Inc Class C", "Information Technology"),
    Company("MO", "Altria Group Inc", "Consumer Staples"),
    Company("AMZN", "Amazon.com Inc.", "Consumer Discretionary"),
    Company("AEE", "Ameren Corp", "Utilities"),
    Company("AAL", "American Airlines Group", "Industrials"),
    Company("AEP", "American Electric Power", "Utilities"),
    Company("AXP", "American Express Co", "Financials"),
    Company("AIG", "American International Group, Inc.", "Financials"),
    Company("AMT", "American Tower Corp A", "Real Estate"),
    Company("AWK", "American Water Works Company Inc", "Utilities"),
    Company("AMP", "Ameriprise Financial", "Financials"),
    Company("ABC", "AmerisourceBergen Corp", "Health Care"),
    Company("AME", "AMETEK Inc.", "Industrials"),
    Company("AMGN", "Amgen Inc.", "Health Care"),
    Company("APH", "Amphenol Corp", "Information Technology"),
    Company("APC", "Anadarko Petroleum Corp", "Energy"),
    Company("ADI", "Analog Devices, Inc.", "Information Technology"),
    Company("ANDV", "Andeavor", "Energy"),
    Company("ANSS", "ANSYS", "Information Technology"),
    Company("ANTM", "Anthem Inc.", "Health Care"),
    Company("AON", "Aon plc", "Financials"),
    Company("APA", "Apache Corporation", "Energy"),
    Company("AIV", "Apartment Investment & Management", "Real Estate"),
    Company("AAPL", "Apple Inc.", "Information Technology"),
    Company("AMAT", "Applied Materials Inc.", "Information Technology"),
    Company("APTV", "Aptiv Plc", "Consumer Discretionary"),
    Company("ADM", "Archer-Daniels-Midland Co", "Consumer Staples"),
    Company("ARNC", "Arconic Inc.", "Industrials"),
    Company("AJG", "Arthur J. Gallagher & Co.", "Financials"),
    Company("AIZ", "Assurant Inc.", "Financials"),
    Company("T", "AT&T Inc.", "Telecommunication Services"),
    Company("ADSK", "Autodesk Inc.", "Information Technology"),
    Company("ADP", "Automatic Data Processing", "Information Technology"),
    Company("AZO", "AutoZone Inc", "Consumer Discretionary"),
    Company("AVB", "AvalonBay Communities, Inc.", "Real Estate"),
    Company("AVY", "Avery Dennison Corp", "Materials"),
    Company("BHGE", "Baker Hughes, a GE Company", "Energy"),
    Company("BLL", "Ball Corp", "Materials"),
    Company("BAC", "Bank of America Corp", "Financials"),
    Company("BAX", "Baxter International Inc.", "Health Care"),
    Company("BBT", "BB&T Corporation", "Financials"),
    Company("BDX", "Becton Dickinson", "Health Care"),
    Company("BRK.B", "Berkshire Hathaway", "Financials"),
    Company("BBY", "Best Buy Co. Inc.", "Consumer Discretionary"),
    Company("BIIB", "Biogen Inc.", "Health Care"),
    Company("BLK", "BlackRock", "Financials"),
    Company("HRB", "Block H&R", "Financials"),
    Company("BA", "Boeing Company", "Industrials"),
    Company("BKNG", "Booking Holdings Inc", "Consumer Discretionary"),
    Company("BWA", "BorgWarner", "Consumer Discretionary"),
    Company("BXP", "Boston Properties", "Real Estate"),
    Company("BSX", "Boston Scientific", "Health Care"),
    Company("BHF", "Brighthouse Financial Inc", "Financials"),
    Company("BMY", "Bristol-Myers Squibb", "Health Care"),
    Company("AVGO", "Broadcom", "Information Technology"),
    Company("BF.B", "Brown-Forman Corp.", "Consumer Staples"),
    Company("CHRW", "C. H. Robinson Worldwide", "Industrials"),
    Company("CA", "CA, Inc.", "Information Technology"),
    Company("COG", "Cabot Oil & Gas", "Energy"),
    Company("CDNS", "Cadence Design Systems", "Information Technology"),
    Company("CPB", "Campbell Soup", "Consumer Staples"),
    Company("COF", "Capital One Financial", "Financials"),
    Company("CAH", "Cardinal Health Inc.", "Health Care"),
    Company("KMX", "Carmax Inc", "Consumer Discretionary"),
    Company("CCL", "Carnival Corp.", "Consumer Discretionary"),
    Company("CAT", "Caterpillar Inc.", "Industrials"),
    Company("CBOE", "Cboe Global Markets", "Financials"),
    Company("CBRE", "CBRE Group", "Real Estate"),
    Company("CBS", "CBS Corp.", "Consumer Discretionary"),
    Company("CELG", "Celgene Corp.", "Health Care"),
    Company("CNC", "Centene Corporation", "Health Care"),
    Company("CNP", "CenterPoint Energy", "Utilities"),
    Company("CTL", "CenturyLink Inc", "Telecommunication Services"),
    Company("CERN", "Cerner", "Health Care"),
    Company("CF", "CF Industries Holdings Inc", "Materials"),
    Company("SCHW", "Charles Schwab Corporation", "Financials"),
    Company("CHTR", "Charter Communications", "Consumer Discretionary"),
    Company("CVX", "Chevron Corp.", "Energy"),
    Company("CMG", "Chipotle Mexican Grill", "Consumer Discretionary"),
    Company("CB", "Chubb Limited", "Financials"),
    Company("CHD", "Church & Dwight", "Consumer Staples"),
    Company("CI", "CIGNA Corp.", "Health Care"),
    Company("XEC", "Cimarex Energy", "Energy"),
    Company("CINF", "Cincinnati Financial", "Financials"),
    Company("CTAS", "Cintas Corporation", "Industrials"),
    Company("CSCO", "Cisco Systems", "Information Technology"),
    Company("C", "Citigroup Inc.", "Financials"),
      Company("CFG", "Citizens Financial Group", "Financials"),
      Company("CTXS", "Citrix Systems", "Information Technology"),
      Company("CME", "CME Group Inc.", "Financials"),
      Company("CMS", "CMS Energy", "Utilities"),
      Company("KO", "Coca-Cola Company (The)", "Consumer Staples"),
      Company("CTSH", "Cognizant Technology Solutions", "Information Technology"),
      Company("CL", "Colgate-Palmolive", "Consumer Staples"),
      Company("CMCSA", "Comcast Corp.", "Consumer Discretionary"),
      Company("CMA", "Comerica Inc.", "Financials"),
      Company("CAG", "Conagra Brands", "Consumer Staples"),
      Company("CXO", "Concho Resources", "Energy"),
      Company("COP", "ConocoPhillips", "Energy"),
      Company("ED", "Consolidated Edison", "Utilities"),
      Company("STZ", "Constellation Brands", "Consumer Staples"),
      Company("GLW", "Corning Inc.", "Information Technology"),
      Company("COST", "Costco Wholesale Corp.", "Consumer Staples"),
      Company("COTY", "Coty, Inc", "Consumer Staples"),
  Company("CCI", "Crown Castle International Corp.", "Real Estate"),
  Company("CSRA", "CSRA Inc.", "Information Technology"),
  Company("CSX", "CSX Corp.", "Industrials"),
  Company("CMI", "Cummins Inc.", "Industrials"),
  Company("CVS", "CVS Health", "Consumer Staples"),
  Company("DHI", "D. R. Horton", "Consumer Discretionary"),
  Company("DHR", "Danaher Corp.", "Health Care"),
  Company("DRI", "Darden Restaurants", "Consumer Discretionary"),
  Company("DVA", "DaVita Inc.", "Health Care"),
  Company("DE", "Deere & Co.", "Industrials"),
  Company("DAL", "Delta Air Lines Inc.", "Industrials"),
  Company("XRAY", "Dentsply Sirona", "Health Care"),
  Company("DVN", "Devon Energy Corp.", "Energy"),
  Company("DLR", "Digital Realty Trust Inc", "Real Estate"),
  Company("DFS", "Discover Financial Services", "Financials"),
  Company("DISCA", "Discovery Inc. Class A", "Consumer Discretionary"),
//  Company("DISCK", "Discovery Inc. Class C", "Consumer Discretionary"),
  Company("DISH", "Dish Network", "Consumer Discretionary"),
  Company("DG", "Dollar General", "Consumer Discretionary"),
  Company("DLTR", "Dollar Tree", "Consumer Discretionary"),
  Company("D", "Dominion Energy", "Utilities"),
  Company("DOV", "Dover Corp.", "Industrials"),
  Company("DWDP", "DowDuPont", "Materials"),
  Company("DPS", "Dr Pepper Snapple Group", "Consumer Staples"),
  Company("DTE", "DTE Energy Co.", "Utilities"),
  Company("DUK", "Duke Energy", "Utilities"),
  Company("DRE", "Duke Realty Corp", "Real Estate"),
  Company("DXC", "DXC Technology", "Information Technology"),
  Company("ETFC", "E*Trade", "Financials"),
  Company("EMN", "Eastman Chemical", "Materials"),
  Company("ETN", "Eaton Corporation", "Industrials"),
  Company("EBAY", "eBay Inc.", "Information Technology"),
  Company("ECL", "Ecolab Inc.", "Materials"),
  Company("EIX", "Edison Int'l", "Utilities"),
  Company("EW", "Edwards Lifesciences", "Health Care"),
  Company("EA", "Electronic Arts", "Information Technology"),
  Company("EMR", "Emerson Electric Company", "Industrials"),
  Company("ETR", "Entergy Corp.", "Utilities"),
  Company("EVHC", "Envision Healthcare", "Health Care"),
  Company("EOG", "EOG Resources", "Energy"),
  Company("EQT", "EQT Corporation", "Energy"),
  Company("EFX", "Equifax Inc.", "Industrials"),
  Company("EQIX", "Equinix", "Real Estate"),
  Company("EQR", "Equity Residential", "Real Estate"),
  Company("ESS", "Essex Property Trust, Inc.", "Real Estate"),
  Company("EL", "Estee Lauder Cos.", "Consumer Staples"),
  Company("RE", "Everest Re Group Ltd.", "Financials"),
  Company("ES", "Eversource Energy", "Utilities"),
  Company("EXC", "Exelon Corp.", "Utilities"),
  Company("EXPE", "Expedia Inc.", "Consumer Discretionary"),
  Company("EXPD", "Expeditors International", "Industrials"),
  Company("ESRX", "Express Scripts", "Health Care"),
  Company("EXR", "Extra Space Storage", "Real Estate"),
  Company("XOM", "Exxon Mobil Corp.", "Energy"),
  Company("FFIV", "F5 Networks", "Information Technology"),
  Company("FB", "Facebook, Inc.", "Information Technology"),
  Company("FAST", "Fastenal Co", "Industrials"),
  Company("FRT", "Federal Realty Investment Trust", "Real Estate"),
  Company("FDX", "FedEx Corporation", "Industrials"),
  Company("FIS", "Fidelity National Information Services", "Information Technology"),
  Company("FITB", "Fifth Third Bancorp", "Financials"),
  Company("FE", "FirstEnergy Corp", "Utilities"),
  Company("FISV", "Fiserv Inc", "Information Technology"),
  Company("FLIR", "FLIR Systems", "Information Technology"),
  Company("FLS", "Flowserve Corporation", "Industrials"),
  Company("FLR", "Fluor Corp.", "Industrials"),
  Company("FMC", "FMC Corporation", "Materials"),
  Company("FL", "Foot Locker Inc", "Consumer Discretionary"),
  Company("F", "Ford Motor", "Consumer Discretionary"),
  Company("FTV", "Fortive Corp", "Industrials"),
  Company("FBHS", "Fortune Brands Home & Security", "Industrials"),
  Company("BEN", "Franklin Resources", "Financials"),
  Company("FCX", "Freeport-McMoRan Inc.", "Materials"),
  Company("GPS", "Gap Inc.", "Consumer Discretionary"),
  Company("GRMN", "Garmin Ltd.", "Consumer Discretionary"),
  Company("IT", "Gartner Inc", "Information Technology"),
  Company("GD", "General Dynamics", "Industrials"),
  Company("GE", "General Electric", "Industrials"),
  Company("GGP", "General Growth Properties Inc.", "Real Estate"),
  Company("GIS", "General Mills", "Consumer Staples"),
  Company("GM", "General Motors", "Consumer Discretionary"),
  Company("GPC", "Genuine Parts", "Consumer Discretionary"),
  Company("GILD", "Gilead Sciences", "Health Care"),
  Company("GPN", "Global Payments Inc.", "Information Technology"),
  Company("GS", "Goldman Sachs Group", "Financials"),
  Company("GT", "Goodyear Tire & Rubber", "Consumer Discretionary"),
  Company("GWW", "Grainger (W.W.) Inc.", "Industrials"),
  Company("HAL", "Halliburton Co.", "Energy"),
  Company("HBI", "Hanesbrands Inc", "Consumer Discretionary"),
  Company("HOG", "Harley-Davidson", "Consumer Discretionary"),
  Company("HRS", "Harris Corporation", "Information Technology"),
  Company("HIG", "Hartford Financial Svc.Gp.", "Financials"),
  Company("HAS", "Hasbro Inc.", "Consumer Discretionary"),
  Company("HCA", "HCA Holdings", "Health Care"),
  Company("HCP", "HCP Inc.", "Real Estate"),
  Company("HP", "Helmerich & Payne", "Energy"),
  Company("HSIC", "Henry Schein", "Health Care"),
  Company("HES", "Hess Corporation", "Energy"),
  Company("HPE", "Hewlett Packard Enterprise", "Information Technology"),
  Company("HLT", "Hilton Worldwide Holdings Inc", "Consumer Discretionary"),
  Company("HOLX", "Hologic", "Health Care"),
  Company("HD", "Home Depot", "Consumer Discretionary"),
  Company("HON", "Honeywell Int'l Inc.", "Industrials"),
  Company("HRL", "Hormel Foods Corp.", "Consumer Staples"),
  Company("HST", "Host Hotels & Resorts", "Real Estate"),
  Company("HPQ", "HP Inc.", "Information Technology"),
  Company("HUM", "Humana Inc.", "Health Care"),
  Company("HBAN", "Huntington Bancshares", "Financials"),
  Company("HII", "Huntington Ingalls Industries", "Industrials"),
  Company("IDXX", "IDEXX Laboratories", "Health Care"),
  Company("INFO", "IHS Markit Ltd.", "Industrials"),
  Company("ITW", "Illinois Tool Works", "Industrials"),
  Company("ILMN", "Illumina Inc", "Health Care"),
  Company("INCY", "Incyte", "Health Care"),
  Company("IR", "Ingersoll-Rand PLC", "Industrials"),
  Company("INTC", "Intel Corp.", "Information Technology"),
  Company("ICE", "Intercontinental Exchange", "Financials"),
  Company("IBM", "International Business Machines", "Information Technology"),
  Company("IP", "International Paper", "Materials"),
  Company("IPG", "Interpublic Group", "Consumer Discretionary"),
  Company("IFF", "Intl Flavors & Fragrances", "Materials"),
  Company("INTU", "Intuit Inc.", "Information Technology"),
  Company("ISRG", "Intuitive Surgical Inc.", "Health Care"),
  Company("IVZ", "Invesco Ltd.", "Financials"),
  Company("IPGP", "IPG Photonics Corp.", "Information Technology"),
  Company("IQV", "IQVIA Holdings Inc.", "Health Care"),
  Company("IRM", "Iron Mountain Incorporated", "Real Estate"),
  Company("JBHT", "J. B. Hunt Transport Services", "Industrials"),
  Company("JEC", "Jacobs Engineering Group", "Industrials"),
  Company("SJM", "JM Smucker", "Consumer Staples"),
  Company("JNJ", "Johnson & Johnson", "Health Care"),
  Company("JCI", "Johnson Controls International", "Industrials"),
  Company("JPM", "JPMorgan Chase & Co.", "Financials"),
  Company("JNPR", "Juniper Networks", "Information Technology"),
  Company("KSU", "Kansas City Southern", "Industrials"),
  Company("K", "Kellogg Co.", "Consumer Staples"),
  Company("KEY", "KeyCorp", "Financials"),
  Company("KMB", "Kimberly-Clark", "Consumer Staples"),
  Company("KIM", "Kimco Realty", "Real Estate"),
  Company("KMI", "Kinder Morgan", "Energy"),
  Company("KLAC", "KLA-Tencor Corp.", "Information Technology"),
  Company("KSS", "Kohl's Corp.", "Consumer Discretionary"),
  Company("KHC", "Kraft Heinz Co", "Consumer Staples"),
  Company("KR", "Kroger Co.", "Consumer Staples"),
  Company("LB", "L Brands Inc.", "Consumer Discretionary"),
  Company("LLL", "L-3 Communications Holdings", "Industrials"),
  Company("LH", "Laboratory Corp. of America Holding", "Health Care"),
  Company("LRCX", "Lam Research", "Information Technology"),
  Company("LEG", "Leggett & Platt", "Consumer Discretionary"),
  Company("LEN", "Lennar Corp.", "Consumer Discretionary"),
  Company("LUK", "Leucadia National Corp.", "Financials"),
  Company("LLY", "Lilly (Eli) & Co.", "Health Care"),
  Company("LNC", "Lincoln National", "Financials"),
  Company("LKQ", "LKQ Corporation", "Consumer Discretionary"),
  Company("LMT", "Lockheed Martin Corp.", "Industrials"),
  Company("L", "Loews Corp.", "Financials"),
  Company("LOW", "Lowe's Cos.", "Consumer Discretionary"),
  Company("LYB", "LyondellBasell", "Materials"),
  Company("MTB", "M&T Bank Corp.", "Financials"),
  Company("MAC", "Macerich", "Real Estate"),
  Company("M", "Macy's Inc.", "Consumer Discretionary"),
  Company("MRO", "Marathon Oil Corp.", "Energy"),
  Company("MPC", "Marathon Petroleum", "Energy"),
  Company("MAR", "Marriott Int'l.", "Consumer Discretionary"),
  Company("MMC", "Marsh & McLennan", "Financials"),
  Company("MLM", "Martin Marietta Materials", "Materials"),
  Company("MAS", "Masco Corp.", "Industrials"),
  Company("MA", "Mastercard Inc.", "Information Technology"),
  Company("MAT", "Mattel Inc.", "Consumer Discretionary"),
  Company("MKC", "McCormick & Co.", "Consumer Staples"),
  Company("MCD", "McDonald's Corp.", "Consumer Discretionary"),
  Company("MCK", "McKesson Corp.", "Health Care"),
  Company("MDT", "Medtronic plc", "Health Care"),
  Company("MRK", "Merck & Co.", "Health Care"),
  Company("MET", "MetLife Inc.", "Financials"),
  Company("MTD", "Mettler Toledo", "Health Care"),
  Company("MGM", "MGM Resorts International", "Consumer Discretionary"),
  Company("KORS", "Michael Kors Holdings", "Consumer Discretionary"),
  Company("MCHP", "Microchip Technology", "Information Technology"),
  Company("MU", "Micron Technology", "Information Technology"),
  Company("MSFT", "Microsoft Corp.", "Information Technology"),
  Company("MAA", "Mid-America Apartments", "Real Estate"),
  Company("MHK", "Mohawk Industries", "Consumer Discretionary"),
  Company("TAP", "Molson Coors Brewing Company", "Consumer Staples"),
  Company("MDLZ", "Mondelez International", "Consumer Staples"),
  Company("MON", "Monsanto Co.", "Materials"),
  Company("MNST", "Monster Beverage", "Consumer Staples"),
  Company("MCO", "Moody's Corp", "Financials"),
  Company("MS", "Morgan Stanley", "Financials"),
  Company("MSI", "Motorola Solutions Inc.", "Information Technology"),
  Company("MYL", "Mylan N.V.", "Health Care"),
  Company("NDAQ", "Nasdaq, Inc.", "Financials"),
  Company("NOV", "National Oilwell Varco Inc.", "Energy"),
  Company("NAVI", "Navient", "Financials"),
  Company("NKTR", "Nektar Therapeutics", "Health Care"),
  Company("NTAP", "NetApp", "Information Technology"),
  Company("NFLX", "Netflix Inc.", "Information Technology"),
  Company("NWL", "Newell Brands", "Consumer Discretionary"),
  Company("NFX", "Newfield Exploration Co", "Energy"),
  Company("NEM", "Newmont Mining Corporation", "Materials"),
  Company("NWSA", "News Corp. Class A", "Consumer Discretionary"),
//  Company("NWS", "News Corp. Class B", "Consumer Discretionary"),
  Company("NEE", "NextEra Energy", "Utilities"),
  Company("NLSN", "Nielsen Holdings", "Industrials"),
  Company("NKE", "Nike", "Consumer Discretionary"),
  Company("NI", "NiSource Inc.", "Utilities"),
  Company("NBL", "Noble Energy Inc", "Energy"),
  Company("JWN", "Nordstrom", "Consumer Discretionary"),
  Company("NSC", "Norfolk Southern Corp.", "Industrials"),
  Company("NTRS", "Northern Trust Corp.", "Financials"),
  Company("NOC", "Northrop Grumman Corp.", "Industrials"),
  Company("NCLH", "Norwegian Cruise Line", "Consumer Discretionary"),
  Company("NRG", "NRG Energy", "Utilities"),
  Company("NUE", "Nucor Corp.", "Materials"),
  Company("NVDA", "Nvidia Corporation", "Information Technology"),
  Company("ORLY", "O'Reilly Automotive", "Consumer Discretionary"),
  Company("OXY", "Occidental Petroleum", "Energy"),
  Company("OMC", "Omnicom Group", "Consumer Discretionary"),
  Company("OKE", "ONEOK", "Energy"),
  Company("ORCL", "Oracle Corp.", "Information Technology"),
  Company("PCAR", "PACCAR Inc.", "Industrials"),
  Company("PKG", "Packaging Corporation of America", "Materials"),
  Company("PH", "Parker-Hannifin", "Industrials"),
  Company("PAYX", "Paychex Inc.", "Information Technology"),
  Company("PYPL", "PayPal", "Information Technology"),
  Company("PNR", "Pentair Ltd.", "Industrials"),
  Company("PBCT", "People's United Financial", "Financials"),
  Company("PEP", "PepsiCo Inc.", "Consumer Staples"),
  Company("PKI", "PerkinElmer", "Health Care"),
  Company("PRGO", "Perrigo", "Health Care"),
  Company("PFE", "Pfizer Inc.", "Health Care"),
  Company("PCG", "PG&E Corp.", "Utilities"),
  Company("PM", "Philip Morris International", "Consumer Staples"),
  Company("PSX", "Phillips 66", "Energy"),
  Company("PNW", "Pinnacle West Capital", "Utilities"),
  Company("PXD", "Pioneer Natural Resources", "Energy"),
  Company("PNC", "PNC Financial Services", "Financials"),
  Company("RL", "Polo Ralph Lauren Corp.", "Consumer Discretionary"),
  Company("PPG", "PPG Industries", "Materials"),
  Company("PPL", "PPL Corp.", "Utilities"),
  Company("PX", "Praxair Inc.", "Materials"),
  Company("PFG", "Principal Financial Group", "Financials"),
  Company("PG", "Procter & Gamble", "Consumer Staples"),
  Company("PGR", "Progressive Corp.", "Financials"),
  Company("PLD", "Prologis", "Real Estate"),
  Company("PRU", "Prudential Financial", "Financials"),
  Company("PEG", "Public Serv. Enterprise Inc.", "Utilities"),
  Company("PSA", "Public Storage", "Real Estate"),
  Company("PHM", "Pulte Homes Inc.", "Consumer Discretionary"),
  Company("PVH", "PVH Corp.", "Consumer Discretionary"),
  Company("QRVO", "Qorvo", "Information Technology"),
  Company("QCOM", "QUALCOMM Inc.", "Information Technology"),
  Company("PWR", "Quanta Services Inc.", "Industrials"),
  Company("DGX", "Quest Diagnostics", "Health Care"),
  Company("RRC", "Range Resources Corp.", "Energy"),
  Company("RJF", "Raymond James Financial Inc.", "Financials"),
  Company("RTN", "Raytheon Co.", "Industrials"),
  Company("O", "Realty Income Corporation", "Real Estate"),
  Company("RHT", "Red Hat Inc.", "Information Technology"),
  Company("REG", "Regency Centers Corporation", "Real Estate"),
  Company("REGN", "Regeneron", "Health Care"),
  Company("RF", "Regions Financial Corp.", "Financials"),
  Company("RSG", "Republic Services Inc", "Industrials"),
  Company("RMD", "ResMed", "Health Care"),
  Company("RHI", "Robert Half International", "Industrials"),
  Company("ROK", "Rockwell Automation Inc.", "Industrials"),
  Company("COL", "Rockwell Collins", "Industrials"),
  Company("ROP", "Roper Technologies", "Industrials"),
  Company("ROST", "Ross Stores", "Consumer Discretionary"),
  Company("RCL", "Royal Caribbean Cruises Ltd", "Consumer Discretionary"),
  Company("SPGI", "S&P Global, Inc.", "Financials"),
  Company("CRM", "Salesforce.com", "Information Technology"),
  Company("SBAC", "SBA Communications", "Real Estate"),
  Company("SCG", "SCANA Corp", "Utilities"),
  Company("SLB", "Schlumberger Ltd.", "Energy"),
  Company("STX", "Seagate Technology", "Information Technology"),
  Company("SEE", "Sealed Air", "Materials"),
  Company("SRE", "Sempra Energy", "Utilities"),
  Company("SHW", "Sherwin-Williams", "Materials"),
  Company("SPG", "Simon Property Group Inc", "Real Estate"),
  Company("SWKS", "Skyworks Solutions", "Information Technology"),
  Company("SLG", "SL Green Realty", "Real Estate"),
  Company("SNA", "Snap-On Inc.", "Consumer Discretionary"),
  Company("SO", "Southern Co.", "Utilities"),
  Company("LUV", "Southwest Airlines", "Industrials"),
  Company("SWK", "Stanley Black & Decker", "Consumer Discretionary"),
  Company("SBUX", "Starbucks Corp.", "Consumer Discretionary"),
  Company("STT", "State Street Corp.", "Financials"),
  Company("SRCL", "Stericycle Inc", "Industrials"),
  Company("SYK", "Stryker Corp.", "Health Care"),
  Company("STI", "SunTrust Banks", "Financials"),
  Company("SIVB", "SVB Financial", "Financials"),
  Company("SYMC", "Symantec Corp.", "Information Technology"),
  Company("SYF", "Synchrony Financial", "Financials"),
  Company("SNPS", "Synopsys Inc.", "Information Technology"),
  Company("SYY", "Sysco Corp.", "Consumer Staples"),
  Company("TROW", "T. Rowe Price Group", "Financials"),
  Company("TTWO", "Take-Two Interactive", "Information Technology"),
  Company("TPR", "Tapestry, Inc.", "Consumer Discretionary"),
  Company("TGT", "Target Corp.", "Consumer Discretionary"),
  Company("TEL", "TE Connectivity Ltd.", "Information Technology"),
  Company("FTI", "TechnipFMC", "Energy"),
  Company("TXN", "Texas Instruments", "Information Technology"),
  Company("TXT", "Textron Inc.", "Industrials"),
  Company("BK", "The Bank of New York Mellon Corp.", "Financials"),
  Company("CLX", "The Clorox Company", "Consumer Staples"),
  Company("COO", "The Cooper Companies", "Health Care"),
  Company("HSY", "The Hershey Company", "Consumer Staples"),
  Company("MOS", "The Mosaic Company", "Materials"),
  Company("TRV", "The Travelers Companies Inc.", "Financials"),
  Company("DIS", "The Walt Disney Company", "Consumer Discretionary"),
  Company("TMO", "Thermo Fisher Scientific", "Health Care"),
  Company("TIF", "Tiffany & Co.", "Consumer Discretionary"),
  Company("TWX", "Time Warner Inc.", "Consumer Discretionary"),
  Company("TJX", "TJX Companies Inc.", "Consumer Discretionary"),
  Company("TMK", "Torchmark Corp.", "Financials"),
  Company("TSS", "Total System Services", "Information Technology"),
  Company("TSCO", "Tractor Supply Company", "Consumer Discretionary"),
  Company("TDG", "TransDigm Group", "Industrials"),
  Company("TRIP", "TripAdvisor", "Consumer Discretionary"),
  Company("FOXA", "Twenty-First Century Fox Class A", "Consumer Discretionary"),
//  Company("FOX", "Twenty-First Century Fox Class B", "Consumer Discretionary"),
  Company("TSN", "Tyson Foods", "Consumer Staples"),
  Company("USB", "U.S. Bancorp", "Financials"),
  Company("UDR", "UDR Inc", "Real Estate"),
  Company("ULTA", "Ulta Beauty", "Consumer Discretionary"),
  Company("UAA", "Under Armour Class A", "Consumer Discretionary"),
//  Company("UA", "Under Armour Class C", "Consumer Discretionary"),
  Company("UNP", "Union Pacific", "Industrials"),
  Company("UAL", "United Continental Holdings", "Industrials"),
  Company("UNH", "United Health Group Inc.", "Health Care"),
  Company("UPS", "United Parcel Service", "Industrials"),
  Company("URI", "United Rentals, Inc.", "Industrials"),
  Company("UTX", "United Technologies", "Industrials"),
  Company("UHS", "Universal Health Services, Inc.", "Health Care"),
  Company("UNM", "Unum Group", "Financials"),
  Company("VFC", "V.F. Corp.", "Consumer Discretionary"),
  Company("VLO", "Valero Energy", "Energy"),
  Company("VAR", "Varian Medical Systems", "Health Care"),
  Company("VTR", "Ventas Inc", "Real Estate"),
  Company("VRSN", "Verisign Inc.", "Information Technology"),
  Company("VRSK", "Verisk Analytics", "Industrials"),
  Company("VZ", "Verizon Communications", "Telecommunication Services"),
  Company("VRTX", "Vertex Pharmaceuticals Inc", "Health Care"),
  Company("VIAB", "Viacom Inc.", "Consumer Discretionary"),
  Company("V", "Visa Inc.", "Information Technology"),
  Company("VNO", "Vornado Realty Trust", "Real Estate"),
  Company("VMC", "Vulcan Materials", "Materials"),
  Company("WMT", "Wal-Mart Stores", "Consumer Staples"),
  Company("WBA", "Walgreens Boots Alliance", "Consumer Staples"),
  Company("WM", "Waste Management Inc.", "Industrials"),
  Company("WAT", "Waters Corporation", "Health Care"),
  Company("WEC", "Wec Energy Group Inc", "Utilities"),
  Company("WFC", "Wells Fargo", "Financials"),
  Company("WELL", "Welltower Inc.", "Real Estate"),
  Company("WDC", "Western Digital", "Information Technology"),
  Company("WU", "Western Union Co", "Information Technology"),
  Company("WRK", "WestRock Company", "Materials"),
  Company("WY", "Weyerhaeuser Corp.", "Real Estate"),
  Company("WHR", "Whirlpool Corp.", "Consumer Discretionary"),
  Company("WMB", "Williams Cos.", "Energy"),
  Company("WLTW", "Willis Towers Watson", "Financials"),
  Company("WYN", "Wyndham Worldwide", "Consumer Discretionary"),
  Company("WYNN", "Wynn Resorts Ltd", "Consumer Discretionary"),
  Company("XEL", "Xcel Energy Inc", "Utilities"),
  Company("XRX", "Xerox Corp.", "Information Technology"),
  Company("XLNX", "Xilinx Inc", "Information Technology"),
  Company("XL", "XL Capital", "Financials"),
  Company("XYL", "Xylem Inc.", "Industrials"),
  Company("YUM", "Yum! Brands Inc", "Consumer Discretionary"),
  Company("ZBH", "Zimmer Biomet Holdings", "Health Care"),
  Company("ZION", "Zions Bancorp", "Financials"),
  Company("ZTS", "Zoetis", "Health Care"))
}
